import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const css = await readFile(new URL('../styles.css', import.meta.url), 'utf8');
const js = await readFile(new URL('../main.js', import.meta.url), 'utf8');
const bettyHtml = await readFile(new URL('../betty-prompt.html', import.meta.url), 'utf8');
const legacyPromptHtml = await readFile(new URL('../fable-prompt.html', import.meta.url), 'utf8');

test('homepage contains the required positioning and project links', () => {
  assert.match(html, /<span>Ideas<\/span>/);
  assert.match(html, /<span>Impact<\/span>/);
  assert.match(html, /<span class="accent-text">In Real Life<\/span>/);
  assert.doesNotMatch(html, /Ideas\.|Impact\.|In Real Life\./);
  assert.match(html, /data-project-carousel/);
  assert.equal((js.match(/caseStudy: '\/projects\//g) ?? []).length, 3);
  assert.match(html, /aria-label="Three featured projects"/);
  assert.match(html, /Every project begins with a problem worth solving\./);
  assert.match(html, /See My Work/);
  assert.doesNotMatch(html, /Explore Projects|Public learning/);
  assert.match(html, /Work with me/);
  assert.match(js, /Pregnancy information is fragmented/);
  assert.match(js, /A patient-owned pregnancy record that helps women capture what matters/);
  assert.match(js, /Problem<\/dt>/);
  assert.match(js, /What I built<\/dt>/);
  assert.match(js, /What changed<\/dt>/);
  assert.match(js, /What this shows<\/dt>/);
  assert.match(js, /href="\$\{project\.website\}"[^>]*>Visit \$\{project\.name\} <span aria-hidden="true">→<\/span>/);
  assert.doesNotMatch(js, /Read case study|websiteLabel/);
  assert.doesNotMatch(js, /You’ve seen how I think\.|Explore more work/);
  assert.match(html, /You’ve seen how I think\./);
  assert.match(html, /If you’re building something important, I’d love to help\./);
  assert.doesNotMatch(js, /name: 'Mission Control'|name: 'Common Ground'|name: 'Aurelle'/);
  assert.doesNotMatch(js, /visual: 'phone'/);
  assert.match(html, /aria-label="Previous project"/);
  assert.match(html, /aria-label="Next project"/);
  assert.match(html, /class="intro-panel intro-panel-left"><span>Dr Lizzie<\/span>/);
  assert.match(html, /class="intro-panel intro-panel-right"><span>Soyode<\/span>/);
  assert.match(html, /sessionStorage\.getItem\('lizzie-home-intro'\)/);
  assert.match(html, /prefers-reduced-motion: reduce/);
});

test('homepage exposes semantic navigation and a single h1', () => {
  assert.match(html, /<nav[^>]+aria-label="Primary navigation"/);
  assert.equal((html.match(/<h1/g) ?? []).length, 1);
  assert.match(html, /class="skip-link"/);
  const primaryNav = html.match(/<nav id="site-nav"[\s\S]*?<\/nav>/)?.[0] ?? '';
  assert.match(primaryNav, />Home</);
  assert.match(primaryNav, />About</);
  assert.match(primaryNav, />Projects</);
  assert.match(primaryNav, />Free Resources</);
  assert.match(primaryNav, />Contact</);
  assert.doesNotMatch(primaryNav, />Build a Business</);
  assert.ok(primaryNav.indexOf('>Home<') < primaryNav.indexOf('>About<'));
  assert.ok(primaryNav.indexOf('>About<') < primaryNav.indexOf('>Projects<'));
  assert.ok(primaryNav.indexOf('>Projects<') < primaryNav.indexOf('>Free Resources<'));
  assert.ok(primaryNav.indexOf('>Free Resources<') < primaryNav.indexOf('>Contact<'));
  assert.doesNotMatch(primaryNav, />Work<|>Portfolio<|>Media|>Public Voice</);
  assert.match(js, /aria-current/);
  assert.match(js, /new IntersectionObserver\(scheduleActiveNavUpdate/);
  assert.doesNotMatch(js, /window\.scrollY \+ Math\.min/);
  assert.match(html, /data-nav-target="home"/);
  assert.match(html, /AI has shortened the distance between an idea and something real/);
  assert.match(html, /Dr Lizzie Soyode <span>·<\/span> A&amp;E Registrar <span>·<\/span> NHS England Leadership Fellow/);
  assert.match(html, /data-nav-target="contact" data-nav-neutral/);
  assert.match(css, /body\.menu-open \.nav-scrim/);
  assert.match(css, /\.nav-scrim\{background:#fcfcfb;-webkit-backdrop-filter:none;backdrop-filter:none\}/);
  assert.match(css, /body\.menu-closing \.nav-scrim/);
  assert.match(js, /navigationLockId/);
  assert.match(js, /if \(menuOpen \|\| menuClosing \|\| navigationLockId\) return/);
  assert.match(js, /document\.body\.style\.position = 'fixed'/);
  assert.match(js, /element\.setAttribute\('inert', ''\)/);
  assert.match(js, /navigateFromMobileMenu/);
  assert.match(js, /navScrim\?\.addEventListener\('click', \(\) => setMenu\(false/);
  assert.match(js, /masthead\?\.addEventListener\('click'/);
  assert.match(js, /focusTarget\.focus\(\{ preventScroll: true \}\)/);
  assert.doesNotMatch(html, /Speaking and education|Dr Liz London|instagram\.com\/drlizlondon/);
  assert.match(html, /data-nav-target="resources"/);
  assert.match(html, /Simple frameworks and AI tools you can start using today\./);
  assert.doesNotMatch(html, /Experience how I approach ideas, assumptions and decisions/);
  assert.match(html, /data-resource-view="featured"/);
  assert.match(html, /href="\/resources\.html">Browse all free resources/);
  assert.match(js, /import '\.\/resources\.js'/);
  assert.doesNotMatch(html, /The Fable Prompt|href="\/fable-prompt\.html">Copy it now/);
  assert.match(legacyPromptHtml, /window\.location\.replace\(`\/betty-prompt\.html/);
  assert.match(legacyPromptHtml, /rel="canonical" href="https:\/\/drlizlondon\.com\/betty-prompt"/);
  assert.doesNotMatch(html, /data-fable-prompt/);
  assert.match(bettyHtml, /data-copy-fable/);
  assert.match(bettyHtml, /Act as an expert collaborator, not just an assistant\./);
  assert.match(bettyHtml, /Ask a clarifying question only when the missing information would materially change the answer\./);
  assert.match(bettyHtml, /make a reasonable assumption, state it clearly and continue\./);
  assert.match(bettyHtml, /Be honest about uncertainty, limitations and trade-offs\./);
  assert.match(bettyHtml, /not merely finished\./);
  assert.doesNotMatch(bettyHtml, /not just complete|Ask clarifying questions if essential information is missing/);
  assert.match(bettyHtml, /What does it do\?/);
  assert.match(bettyHtml, /data-download-fable/);
  assert.match(bettyHtml, /data-download-fable-pro/);
  assert.match(js, /navigator\.clipboard\.writeText\(prompt\)/);
  assert.match(js, /trackSiteEvent\(['"]site_viewed['"]\)/);
  assert.match(js, /trackSiteEvent\(['"]fable_prompt_viewed['"]\)/);
  assert.match(html, /Send enquiry/);
  assert.match(html, /hello@drlizlondon\.com/);
});

test('styles include mobile and reduced motion treatments', () => {
  assert.match(css, /@media\(max-width:820px\)/);
  assert.match(css, /prefers-reduced-motion:reduce/);
  assert.match(css, /footer\{min-height:36px;padding-top:\.5rem;padding-bottom:\.5rem/);
  assert.match(css, /footer>p:nth-child\(2\)\{display:none\}/);
  assert.match(css, /\.site-header,\.site-header\.is-scrolled\{position:fixed;padding-top:\.55rem;padding-bottom:\.55rem/);
  assert.match(css, /\.site-nav a\{font-size:\.72rem;letter-spacing:\.1em\}/);
  assert.match(css, /touch-action:pan-y/);
  assert.match(css, /min-height:100svh/);
  assert.match(css, /\.projects-section\{min-height:0;padding-top:calc\(3\.65rem/);
  assert.match(css, /max-height:34svh/);
  assert.match(css, /max-width:480px\) and \(max-height:780px/);
  assert.match(css, /height:clamp\(42rem,calc\(100svh - 2\.875rem\),58rem\)/);
  assert.match(css, /grid-template-columns:minmax\(0,1fr\);align-content:center;justify-items:center/);
  assert.match(css, /max-width:480px\) and \(max-height:650px/);
  assert.match(css, /height:calc\(100svh - 4rem\);min-height:31\.5rem;overflow:hidden/);
  assert.match(css, /\.portrait-wrap\{left:50%;transform:translateX\(-50%\)\}/);
  assert.match(css, /\.about-copy\{width:100%;max-width:44rem\}/);
  assert.match(js, /Math\.abs\(distanceX\) >= 48/);
  assert.doesNotMatch(js, /activeSlide\.scrollHeight|viewport\.style\.(?:height|setProperty\(['"]height)/);
  assert.match(css, /@keyframes intro-door-left/);
  assert.match(css, /@keyframes intro-door-right/);
  assert.match(css, /\.intro-panel span\{[^}]*font-family:var\(--serif\)/);
  assert.match(css, /intro-door-left 1\.3s \.5s/);
  assert.match(js, /intro-complete/);
  assert.match(css, /grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);
  assert.match(css, /\.resources-browse-link\{[^}]*grid-area:browse/);
  assert.match(css, /\.resource-card:hover,\.resource-card:focus-within\{background:#faf9f7\}/);
  assert.match(css, /translateX\(3px\)/);
  assert.match(css, /\.resources-section\{display:block;padding-top:3\.5rem;padding-bottom:3\.5rem\}/);
  assert.match(css, /\.resources-browse-link\{min-height:46px;margin-top:1\.1rem/);
  assert.doesNotMatch(css, /\.resource-card:hover[^}]*scale|\.resource-card:hover[^}]*box-shadow/);
});
